version: '3.8'

services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
