spring:
  application:
    name: Library
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/library
    username: postgres
    password: password
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
