spring:
  application:
    name: Library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
